import { userInfo, hostname, platform } from "node:os";
import { writeFileSync } from "node:fs";
import { argv } from 'node:process';
process.env.TZ = "UTC";

const bannerMessage = `/*
 * TagoIO Decoders - (https://tago.io/)
 * -------------------
 * Generated by     :: ${userInfo().username ? userInfo().username : 'Unknown'}
 * Generated at     :: ${new Date()}
 * Machine          :: ${hostname()} <${platform()}> - Node.js ${process.version}
 * -------------------
*/

`;

writeFileSync(String(argv.at(-1)), bannerMessage);
